import { Profile } from "./Profile"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Dashboard() {
  return (
    <Profile />
  )
}
